<a href="https://colab.research.google.com/github/shuklapankaj36/TensorFlow-Course/blob/master/Pankaj_shukla_GuidedLabAssignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
import natsort
import pandas as pd 
import scipy
import math
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import librosa


In [2]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
unzip "/content/only50sample ff1010bird_wav.zip"np

SyntaxError: ignored

In [10]:

labelPath="/content/drive/MyDrive/MULTIMEDIA_TA_DATASET/ff1010bird/ff1010bird_metadata.csv"

temp=pd.read_csv(labelPath, header=None, skiprows=1)
temp.head()

temp2=temp.values

print(temp2.shape)

index=np.argsort(temp2[:,0])
print(index)

sortedValues=temp2[index]
print('sortedValues', sortedValues)

top50LValues=sortedValues[:50]
top50Labels=top50LValues[:,1]
print(top50Labels)

(7690, 2)
[6041 6037 5600 ...  414 2218  777]
sortedValues [[    55      0]
 [    87      0]
 [    99      0]
 ...
 [195598      0]
 [195739      0]
 [195862      0]]
[0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [30]:
dataPath="/content/drive/MyDrive/MULTIMEDIA_TA_DATASET/ff1010bird/only50Sample_ff1010bird_wav/"

listDataDir = os.listdir(dataPath)
#print(listDataDir)
#print(len(listDataDir))

sortedDataDir=natsort.natsorted(listDataDir,reverse=False)
#print("sortedDataDir\n",sortedDataDir)

allRawAudios=[]
for file in range(len(sortedDataDir)):
  #print(file) 
  filePath=dataPath+sortedDataDir[file]
  #print(filePath)
  audio,sr=librosa.load(filePath)
  chunk=audio[4*sr:6*sr]
  print(len(chunk))##take 2 second from each sample instead of whole 10 second
  allRawAudios.append(chunk)


44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100


In [41]:
allFeatures=[]
from numpy import lib
for i in range(len(sortedDataDir)):
  oneSample=allRawAudios[i]
  print(len(oneSample))

  ###MFCC
  feature_mfcc=librosa.feature.mfcc(y=oneSample, sr=sr,n_mfcc=13, hop_length=len(oneSample)+1)
  ### energy
  feature_eng=np.sum(np.square(oneSample)).reshape(-1,1)
  ####ZCR
  feature_zcr=librosa.feature.zero_crossing_rate(oneSample,hop_length=len(oneSample)+1)

  print(feature_mfcc.shape)
  print(feature_eng.shape)
  print(feature_zcr.shape)

  featuresOneFrame=np.concatenate((feature_mfcc, feature_eng, feature_zcr),axis = 0)

  allFeatures.append(featuresOneFrame)


44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)
(1, 1)
44100
(13, 1)
(1, 1)

In [44]:
allFeatures=np.asarray(allFeatures)

print(allFeatures.shape)

allFeatures=np.reshape(allFeatures, (allFeatures.shape[0],allFeatures.shape[1]))

print(allFeatures.shape)

(50, 15, 1)
(50, 15)


In [45]:
#data standarized the data

In [ ]:
### standarize the data
print('before**************')
print(np.mean(allFeatures,axis=0))
print(np.std(allFeatures,axis=0))


from sklearn import preprocessing
allFeature_standardized = preprocessing.scale(allFeatures)

print('after***************')
print(np.mean(allFeature_standardized,axis=0))
print(np.std(allFeature_standardized,axis=0))

In [52]:
X_train, X_test, y_train, y_test = train_test_split(allFeature_standardized, top50Labels, test_size=0.30, random_state=101,shuffle=True)

In [53]:
from sklearn.svm import SVC

model = SVC(kernel='rbf',C=10)
model.fit(X_train,y_train)

SVC(C=10)

In [54]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
#prediction on test data
predictions = model.predict(X_test)
print(predictions)

#different evaluation matrices
print('accuracy_score==',accuracy_score(y_test,predictions))
print('confusion matrix==\n',confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[0 1 0 0 1 0 0 0 0 0 0 0 0 0 1]
accuracy_score== 0.8
confusion matrix==
 [[10  1]
 [ 2  2]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87        11
           1       0.67      0.50      0.57         4

    accuracy                           0.80        15
   macro avg       0.75      0.70      0.72        15
weighted avg       0.79      0.80      0.79        15



In [55]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} ##for rbf kernel
# param_grid = {'C': [0.1,1, 10, 100, 1000], 'kernel': ['sigmoid']} ##for sigmoid kernel
# param_grid = {'C': [0.1,1, 10, 100, 1000], 'kernel': ['linear']} ##for linear kernel
# param_grid = {'C': [0.1,1, 10, 100, 1000], 'degree': [2,3,4,5,6], 'kernel': ['poly']} ##for polynomial kernel

### gamma=Kernel coefficient for ‘rbf’, ‘poly’ and ‘sigmoid’
### c=Regularization parameter

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(kernel='rbf'),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.0

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=2)

In [56]:
print(grid.best_params_)
grid.best_estimator_

{'C': 0.1, 'gamma': 1, 'kernel': 'rbf'}


SVC(C=0.1, gamma=1)

In [57]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))
print(accuracy_score(y_test,grid_predictions))

[[11  0]
 [ 4  0]]
0.7333333333333333


In [62]:
## train SVM models with different kernel
model_linear = SVC(kernel='linear', C=1).fit(X_train, y_train)
model_rbf = SVC(kernel='rbf', gamma=1, C=1).fit(X_train, y_train)
model_poly = SVC(kernel='poly', degree=3, C=1).fit(X_train, y_train)
model_sig = SVC(kernel='sigmoid', C=1).fit(X_train, y_train)

In [59]:
#prediction by each model on test data
linear_pred = model_linear.predict(X_test)
poly_pred = model_poly.predict(X_test)
rbf_pred = model_rbf.predict(X_test)
sig_pred = model_sig.predict(X_test)

# retrieve the accuracy and print it for all 4 kernel functions
accuracy_linear = model_linear.score(X_test, y_test)
accuracy_poly = model_poly.score(X_test, y_test)
accuracy_rbf = model_rbf.score(X_test, y_test)
accuracy_sig = model_sig.score(X_test, y_test)
print('Accuracy Linear Kernel:', accuracy_linear)
print('Accuracy Polynomial Kernel:', accuracy_poly)
print('Accuracy Radial Basis Kernel:', accuracy_rbf)
print('Accuracy Sigmoid Kernel:', accuracy_sig)
      
# creating a confusion matrix
cm_lin = confusion_matrix(y_test, linear_pred)
cm_poly = confusion_matrix(y_test, poly_pred)
cm_rbf = confusion_matrix(y_test, rbf_pred)
cm_sig = confusion_matrix(y_test, sig_pred)
print('cm_lin', '\n',cm_lin, '\n')
print('cm_poly', '\n',cm_poly ,'\n')
print('cm_rbf','\n',cm_rbf ,'\n')
print('cm_sig','\n',cm_sig ,'\n')

Accuracy Linear Kernel: 0.5333333333333333
Accuracy Polynomial Kernel: 0.7333333333333333
Accuracy Radial Basis Kernel: 0.7333333333333333
Accuracy Sigmoid Kernel: 0.7333333333333333
cm_lin 
 [[8 3]
 [4 0]] 

cm_poly 
 [[11  0]
 [ 4  0]] 

cm_rbf 
 [[11  0]
 [ 4  0]] 

cm_sig 
 [[11  0]
 [ 4  0]] 



Report:

Overview:

Birds Sounded data set is used for Identifying  the birds in our  sourounding so to across the sound a SVM based Technique was Applied. In this Project we have imported varios lib. which help us to extracting the voice of the birds and try to predict about the bird. In this method we trained the data set by splitting in the ratio of training (80%) and testing (20%). The model was trained with different kernal which showing a accuracy as such as linear : polynomial: Radial: sigmoid :: 53: 73:73:73. 

The average accuracy of the prediction model is approx 80 percent.which 
is also predicting false result. 